"""Demo ASR provider (tasks/02_AUDIO_PIPELINE.md section 8, 3.1).

Only ever serves the built-in sample library -- reads the deterministic
sidecar transcript fixture for a known sample_id and returns it verbatim as
DiarizedSegment[], with role left "unknown" (never auto-assigned; the
sidecar's `expected_role` is a fixture-authoring aid, not a shortcut past
clinician role confirmation). Never calls an external API, never touches an
arbitrary (non-sample) upload -- see UnavailableASRProvider for that case.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from app.domain.errors import AsrNotConfigured
from app.domain.models import AudioAsset, ClinicalStructure, DiarizedSegment, ExplanationDraft
from app.observability import StageTimer

SAMPLE_FIXTURES_DIR = Path(__file__).resolve().parents[4] / "tests" / "fixtures" / "audio"


def _transcript_path(sample_id: str) -> Path:
    return SAMPLE_FIXTURES_DIR / f"{sample_id}.transcript.json"


def sample_is_available(sample_id: str) -> bool:
    return _transcript_path(sample_id).exists()


def load_demo_structure_and_explanation(sample_id: str) -> tuple[ClinicalStructure, ExplanationDraft]:
    """Reads the sidecar structure/explanation fixtures for a sample --
    docs section 3.1: demo results are read deterministically from fixtures,
    never generated by MockLLMProvider's generic transcript-echo (that would
    lose the curated medication/warning-sign content the fixture author
    wrote to exercise structure/explanation UI review)."""
    structure_data = json.loads(
        (SAMPLE_FIXTURES_DIR / f"{sample_id}.structure.json").read_text(encoding="utf-8")
    )
    explanation_data = json.loads(
        (SAMPLE_FIXTURES_DIR / f"{sample_id}.explanation.json").read_text(encoding="utf-8")
    )
    return ClinicalStructure.model_validate(structure_data), ExplanationDraft.model_validate(explanation_data)


class DemoASRProvider:
    """See app.providers.asr_base.ASRProvider."""

    def transcribe(
        self, audio_asset: AudioAsset, storage_path: str, stage_timer: Optional[StageTimer] = None
    ) -> list[DiarizedSegment]:
        # storage_path/stage_timer are unused here -- demo results always
        # come from the fixed sample_id-keyed sidecar fixture, read from
        # disk in effectively constant time, never from the uploaded file.
        if not audio_asset.sample_id or not sample_is_available(audio_asset.sample_id):
            raise AsrNotConfigured()

        data = json.loads(_transcript_path(audio_asset.sample_id).read_text(encoding="utf-8"))
        return [
            DiarizedSegment(
                id=seg["id"],
                speaker=seg["speaker"],
                role="unknown",
                role_confidence=None,
                start=seg["start"],
                end=seg["end"],
                text=seg["text"],
            )
            for seg in data["segments"]
        ]
